#ifndef PBCPP_VERSION_HPP
#define PBCPP_VERSION_HPP

#define PBCPP_VERSION_STRING "0.1.0"
#define PBCPP_MAJOR_VERSION 0
#define PBCPP_MINOR_VERSION 1
#define PBCPP_PATCH_VERSION 0

#endif //PBCPP_VERSION_HPP
